- tomcat_major: 9
  base_image:
    flavor: rockylinux
    major: 8
  java_major: 11

- tomcat_major: 9
  base_image:
    flavor: rockylinux
    major: 8
  java_major: 17

- tomcat_major: 10
  base_image:
    flavor: rockylinux
    major: 8
  java_major: 11

- tomcat_major: 10
  base_image:
    flavor: rockylinux
    major: 8
  java_major: 17

- tomcat_major: 10
  base_image:
    flavor: rockylinux
    major: 9
  java_major: 17

- tomcat_major: 10
  base_image:
    flavor: rockylinux
    major: 9
  java_major: 21

- tomcat_major: 10
  base_image:
    flavor: rockylinux
    major: 9
  java_major: 25

- tomcat_major: 11
  base_image:
    flavor: rockylinux
    major: 9
  java_major: 21

- tomcat_major: 11
  base_image:
    flavor: rockylinux
    major: 9
  java_major: 25
