# Java 8 Centos 7 Base Image for Alfresco Base Tomcat Image
FROM alfresco/alfresco-base-java:8.0.302-centos-7@sha256:42ca4591007d6ddcc3aebe8404de74117a3eda2a25fbba067f4fb7d2b5381986
ENV JDK_HOME ${JAVA_HOME}/../
