# Java 8 Centos 8 Base Image for Alfresco Base Tomcat Image
FROM alfresco/alfresco-base-java:8.0.292-centos-8-release-candidate@sha256:a460ac601abe2453c93f2082daf53840e6f7ca09ebec6f0b0bd2074cd863563d
