# Java 11 Centos 7 Base Image for Alfresco Base Tomcat Image
FROM alfresco/alfresco-base-java:11-centos-7@sha256:8456bc89df0a619a3186489e0c27a0c7c8fcb7fa722e1453ac0f49a6c8ae99f8
ENV JDK_HOME $JAVA_HOME
