# Java 11 Centos 7 Base Image for Alfresco Base Tomcat Image
FROM alfresco/alfresco-base-java:11.0.13-centos-7@sha256:c1e399d1bbb5d08e0905f1a9ef915ee7c5ea0c0ede11cc9bd7ca98532a9b27fa
ENV JDK_HOME $JAVA_HOME
