# Java 11 Centos 7 Base Image for Alfresco Base Tomcat Image
FROM alfresco/alfresco-base-java:11.0.11-centos-7-release-candidate@sha256:74a56e0f29d53b2b46ce944cfbe3fb3d2fbd71a34179a831fd37d674e89f40d5
